apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portability
  name: portability-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portability
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portability
    spec:
      containers:
      - image: IMAGE # Replaced by script
        imagePullPolicy: IfNotPresent
        name: portability-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
